import './globals.css'
import { Inter } from 'next/font/google'
import Navbare from '@/app/components/navbare/Nav'
import Footer from'@/app/components/foodage/Fooder'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbare />
        
        {children}

        <Footer />
        </body>
    </html>
  )
}
